@base = http://localhost:62204/api

###
GET {{base}}/user

###
GET {{base}}/user/99


###
POST {{base}}/user
Accept: application/json, text/javascript, */*; q=0.01
Content-Type: application/json; charset=UTF-8

{
    "Id":101,
    "Name":"User 101",
    "EmailId": "user_post01@example.com",
    "dateOfBirth":"1999-02-02T00:00:00+00:00",
    "UserRole":2
}

